name = "williamspurlock-portfolio"
compatibility_date = "2024-03-31"

[site]
bucket = "./dist"
include = ["dist/**/*"]

# Pages specific configuration
[pages]
build_output_dir = "dist"
build_command = "npm run build" 