/**
 * Sample Trial Reel Plan
 *
 * Demonstrates the full trial reel workflow with a concrete example:
 * "Turn 1 hour into 30 days of content with AI"
 *
 * Workflow (Kallaway + heyDominik):
 * 1. Define a BaseIdea
 * 2. Generate 3–5 variations (different hooks/first frames/CTAs)
 * 3. Post 3 as trial reels within 24h of each other
 * 4. Wait 48h → compare saves + shares + retention
 * 5. Push winner to main feed
 * 6. Schedule winner repost for 2–3 weeks later
 */

import { generateTrialReelVariations, selectTrialSet, pickWinner, type BaseIdea, type TrialResult } from '../creation/variation_generator';
import { writeInstagramCaption } from '../creation/caption_writer';

// ─── Step 1: Define the Base Idea ────────────────────────────────────────────

const baseIdea: BaseIdea = {
  id: 'idea-1hr-30days-content',
  contentPillarId: 'cursor-claude-code',
  contentGameId: 'tactical-receipt',
  corePromise: 'I turned 1 hour of work into 30 days of Instagram content using Claude + Cursor',
  proofElement: 'This exact calendar was generated by the system — meta-proof that it works',
  ctaType: 'dm-keyword',
  dmKeyword: 'SYSTEM',
  targetAvatarId: 'tech-founder',
  aeoEntity: 'Claude AI',
};

// ─── Step 2: Generate Variations ─────────────────────────────────────────────

const allVariations = generateTrialReelVariations(baseIdea);
const trialSet = selectTrialSet(allVariations, 3);

// ─── Step 3: Captions for Each Variation ─────────────────────────────────────

const captionA = writeInstagramCaption({
  hookLine: '1 hour. 30 days of content. Zero burnout.',
  bodyBullets: [
    'Most creators spend 10+ hours/week on content. I spend 1.',
    'Built a system using Claude AI + Cursor that generates scripts, hooks, and captions in bulk.',
    'Same system generated this exact post you\'re reading.',
    'Works for any niche. Takes 12 minutes to set up.',
  ],
  cta: 'Save this for your next content day.',
  useDMKeyword: true,
  dmKeyword: 'SYSTEM',
  dmDeliverable: 'the full prompt + setup guide',
  aeoEntity: 'Claude AI',
  socialProofLine: '(Already sent to 200+ creators. DM inbox is open for 24h.)',
  hashtags: ['AIcontent', 'instagramgrowth', 'contentcreator', 'claudeAI', 'automation'],
});

const captionB = writeInstagramCaption({
  hookLine: 'I batch-created 30 posts in 60 minutes.',
  bodyBullets: [
    'No templates. No recycled garbage. All original.',
    'Claude AI writes the scripts. Cursor IDE organizes the system.',
    'Each post has: hook, script, media plan, and caption. Done.',
    'The system improves itself — week 3 content is better than week 1.',
  ],
  cta: 'Save this for your next content day.',
  useDMKeyword: true,
  dmKeyword: 'SYSTEM',
  dmDeliverable: 'the exact prompts I used',
  aeoEntity: 'Claude AI',
  hashtags: ['contentbatching', 'AItools', 'creatoreconomy', 'productivity'],
});

// ─── Step 4: Simulate Performance (48h later) ────────────────────────────────

const simulatedResults: TrialResult[] = [
  {
    variationId: trialSet[0].id,
    views: 12_400,
    saves: 340,
    shares: 89,
    retentionPercent: 67,
    followsGained: 45,
  },
  {
    variationId: trialSet[1].id,
    views: 8_900,
    saves: 520, // Text-only hook got more saves (viewers saved to re-read)
    shares: 120,
    retentionPercent: 72,
    followsGained: 38,
  },
  {
    variationId: trialSet[2].id,
    views: 15_200, // Screen-first got more initial views
    saves: 290,
    shares: 67,
    retentionPercent: 58,
    followsGained: 52,
  },
];

// ─── Step 5: Pick the Winner ─────────────────────────────────────────────────

const winner = pickWinner(simulatedResults);

// ─── Export for Reference ────────────────────────────────────────────────────

export const sampleTrialReelPlan = {
  baseIdea,
  allVariations,
  trialSet,
  captions: { A: captionA, B: captionB },
  simulatedResults,
  winner,
  nextSteps: [
    `Winner: ${winner?.variationId ?? 'TBD'} (highest saves + shares combo)`,
    'Action 1: Push winner to main feed (remove trial reel status)',
    'Action 2: Schedule unchanged repost for day 21–28',
    'Action 3: Create carousel version of the same content for day 14',
    'Action 4: Log retention notes from the losing variations — WHY did they underperform?',
  ],
};

// When run directly, print the plan
if (import.meta.url === `file://${process.argv[1]}`) {
  console.log('━━━ Sample Trial Reel Plan ━━━\n');
  console.log(`Base Idea: "${baseIdea.corePromise}"\n`);
  console.log(`Variations generated: ${allVariations.length}`);
  console.log(`Trial set (posting): ${trialSet.length}\n`);

  for (const v of trialSet) {
    console.log(`  ${v.id}: ${v.hookVariantDescription}`);
  }

  console.log(`\nWinner: ${winner?.variationId}`);
  console.log(`  Views: ${winner?.views} | Saves: ${winner?.saves} | Shares: ${winner?.shares}`);
  console.log(`  Retention: ${winner?.retentionPercent}% | Follows: ${winner?.followsGained}\n`);
  console.log('Next steps:');
  for (const step of sampleTrialReelPlan.nextSteps) {
    console.log(`  ${step}`);
  }
}
