/**
 * Sample 30-Day Schedule — May 19, 2026 start.
 *
 * Generated by the scheduler, this shows where in the calendar you'll find:
 * - New ideas (the bulk of weeks 1–2)
 * - Trial reel variation days (paired within 24h)
 * - Repost-of-winner days (weeks 3–4)
 * - DM automation posts (1–2/week, each with a keyword CTA)
 *
 * Use this as a template for setting up a Notion or Google Calendar workflow.
 * Import PlannedPost[] into your project management tool and track status.
 */

import { generate30DaySchedule, getPostsByWeek, getPostsByType, getTrialGroups } from '../calendar/scheduler';

// ─── Generate the Schedule ───────────────────────────────────────────────────

const startDate = new Date('2026-05-19T00:00:00');
const schedule = generate30DaySchedule(startDate);

// ─── Analysis ────────────────────────────────────────────────────────────────

const week1 = getPostsByWeek(schedule, 1);
const week2 = getPostsByWeek(schedule, 2);
const week3 = getPostsByWeek(schedule, 3);
const week4 = getPostsByWeek(schedule, 4);

const dmPosts = getPostsByType(schedule, 'dm_automation');
const trialPosts = getPostsByType(schedule, 'trial_reel_variation');
const repostPosts = getPostsByType(schedule, 'winner_repost');
const trialGroups = getTrialGroups(schedule);

// ─── Export ──────────────────────────────────────────────────────────────────

export const sample30DaySchedule = {
  startDate: '2026-05-19',
  endDate: '2026-06-17',
  totalPosts: schedule.length,
  posts: schedule,
  breakdown: {
    week1: { posts: week1.length, reels: week1.filter(p => p.format === 'reel').length, carousels: week1.filter(p => p.format === 'carousel').length },
    week2: { posts: week2.length, reels: week2.filter(p => p.format === 'reel').length, carousels: week2.filter(p => p.format === 'carousel').length },
    week3: { posts: week3.length, reels: week3.filter(p => p.format === 'reel').length, carousels: week3.filter(p => p.format === 'carousel').length },
    week4: { posts: week4.length, reels: week4.filter(p => p.format === 'reel').length, carousels: week4.filter(p => p.format === 'carousel').length },
  },
  dmAutomationPosts: dmPosts.map(p => ({
    date: p.date,
    keyword: p.dmKeyword,
    pillar: p.contentPillarId,
  })),
  trialGroups: [...trialGroups.entries()].map(([id, posts]) => ({
    groupId: id,
    variations: posts.length,
    dates: posts.map(p => p.date),
  })),
  repostSlots: repostPosts.map(p => ({
    date: p.date,
    pillar: p.contentPillarId,
    note: 'Fill with winner from weeks 1–2 after performance data lands',
  })),
};

// ─── Print when run directly ─────────────────────────────────────────────────

if (import.meta.url === `file://${process.argv[1]}`) {
  console.log('━━━ Sample 30-Day Schedule (May 19, 2026) ━━━\n');
  console.log(`Total posts: ${schedule.length}`);
  console.log(`Reels: ${schedule.filter(p => p.format === 'reel').length}`);
  console.log(`Carousels: ${schedule.filter(p => p.format === 'carousel').length}`);
  console.log('');

  console.log('Week breakdown:');
  console.log(`  Week 1: ${week1.length} posts (${week1.filter(p => p.format === 'reel').length}R + ${week1.filter(p => p.format === 'carousel').length}C)`);
  console.log(`  Week 2: ${week2.length} posts (${week2.filter(p => p.format === 'reel').length}R + ${week2.filter(p => p.format === 'carousel').length}C)`);
  console.log(`  Week 3: ${week3.length} posts (${week3.filter(p => p.format === 'reel').length}R + ${week3.filter(p => p.format === 'carousel').length}C)`);
  console.log(`  Week 4: ${week4.length} posts (${week4.filter(p => p.format === 'reel').length}R + ${week4.filter(p => p.format === 'carousel').length}C)`);
  console.log('');

  console.log(`DM automation posts: ${dmPosts.length}`);
  for (const p of dmPosts) {
    console.log(`  ${p.date} — keyword: ${p.dmKeyword} — pillar: ${p.contentPillarId}`);
  }
  console.log('');

  console.log(`Trial reel groups: ${trialGroups.size}`);
  for (const [id, posts] of trialGroups) {
    console.log(`  ${id}: ${posts.length} variations on ${posts.map(p => p.date).join(', ')}`);
  }
  console.log('');

  console.log(`Winner repost slots: ${repostPosts.length}`);
  for (const p of repostPosts) {
    console.log(`  ${p.date} — pillar: ${p.contentPillarId} (fill with week 1-2 winner)`);
  }
  console.log('');

  console.log('━━━ Full Schedule ━━━\n');
  for (const post of schedule) {
    const flags = [
      post.type !== 'new' ? post.type.toUpperCase() : '',
      post.dmKeyword ? `DM:${post.dmKeyword}` : '',
      post.trialGroupId ? `${post.trialGroupId}:v${post.trialVariationNumber}` : '',
    ].filter(Boolean).join(' | ');

    console.log(`  #${String(post.postNumber).padStart(2, '0')} ${post.date} ${post.time} ${post.format.toUpperCase().padEnd(9)} ${post.contentPillarId.padEnd(22)} ${flags}`);
  }
}
